/*
 * Token types for SemanticWalker - Compatibility header for ANTLR3 migration
 * This file provides token constants for backward compatibility
 */

#ifndef SEMANTICWALKERTOKENTYPES_HPP
#define SEMANTICWALKERTOKENTYPES_HPP

// Token type constants in namespace
namespace SemanticWalkerTokenTypes {
    enum {
        T_EOF_ = -1,
        ESC = 4,
        ML_COMMENT = 5,
        SL_COMMENT = 6,
        TI_FCALL = 7,
        TI_FRETURN = 8,
        TI_NULL = 9,
        TI_PARENTHESIS = 10,
        TI_UN_BNOT = 11,
        TI_UN_NEG = 12,
        TI_UN_NOT = 13,
        TI_UN_POS = 14,
        TI_VAR_MATRIX = 15,
        TI_VAR_PRIMITIVE = 16,
        T_ABREC = 17,
        T_ABREP = 18,
        T_ATTR = 19,
        T_BIN_LIT = 20,
        T_BIT_E = 21,
        T_BIT_NOT = 22,
        T_BIT_OU = 23,
        T_BIT_XOU = 24,
        T_CARAC_LIT = 25,
        T_COLON = 26,
        T_COMMA = 27,
        T_DIFERENTE = 28,
        T_DIGIT = 29,
        T_DIV = 30,
        T_FECHAC = 31,
        T_FECHAP = 32,
        T_HEX_LIT = 33,
        T_IDENTIFICADOR = 34,
        T_ID_AUX = 35,
        T_IGUAL = 36,
        T_INTEGER_LIT = 37,
        T_INT_LIT = 38,
        T_KW_ALGORITMO = 39,
        T_KW_ATE = 40,
        T_KW_CARACTERE = 41,
        T_KW_CARACTERES = 42,
        T_KW_DE = 43,
        T_KW_E = 44,
        T_KW_ENQUANTO = 45,
        T_KW_ENTAO = 46,
        T_KW_FACA = 47,
        T_KW_FALSO = 48,
        T_KW_FIM = 49,
        T_KW_FIM_ENQUANTO = 50,
        T_KW_FIM_PARA = 51,
        T_KW_FIM_SE = 52,
        T_KW_FIM_VARIAVEIS = 53,
        T_KW_FUNCAO = 54,
        T_KW_INICIO = 55,
        T_KW_INTEIRO = 56,
        T_KW_INTEIROS = 57,
        T_KW_LITERAIS = 58,
        T_KW_LITERAL = 59,
        T_KW_LOGICO = 60,
        T_KW_LOGICOS = 61,
        T_KW_MATRIZ = 62,
        T_KW_NOT = 63,
        T_KW_OU = 64,
        T_KW_PARA = 65,
        T_KW_PASSO = 66,
        T_KW_REAIS = 67,
        T_KW_REAL = 68,
        T_KW_REPITA = 69,
        T_KW_RETORNE = 70,
        T_KW_SE = 71,
        T_KW_SENAO = 72,
        T_KW_VARIAVEIS = 73,
        T_KW_VERDADEIRO = 74,
        T_LETTER = 75,
        T_LETTER_OR_DIGIT = 76,
        T_MAIOR = 77,
        T_MAIOR_EQ = 78,
        T_MAIS = 79,
        T_MENOR = 80,
        T_MENOR_EQ = 81,
        T_MENOS = 82,
        T_MOD = 83,
        T_MULTIP = 84,
        T_OCTAL_LIT = 85,
        T_REAL_LIT = 86,
        T_SEMICOL = 87,
        T_STRING_LIT = 88,
        T_WS = 89
    };
}

// Note: TIPO_* types are defined in Symbol.hpp

#endif // SEMANTICWALKERTOKENTYPES_HPP
