// Windows x86 assembly header for NASM -f win32
// Uses COFF object format, linked with gcc

_head << "; G-Portugol Windows x86 assembly\n"
         "; Assemble with: nasm -f win32 -o output.obj input.asm\n"
         "; Link with: gcc -m32 -o output.exe output.obj -lkernel32 -lmsvcrt "
         "-nostartfiles -e _start\n"
         "\n"
         "BITS 32\n"
         "\n"
         "; External Windows API functions\n"
         "extern _GetStdHandle@4\n"
         "extern _WriteFile@20\n"
         "extern _ReadFile@20\n"
         "extern _ExitProcess@4\n"
         "\n"
         "%macro exit 1\n"
         "  push dword %1\n"
         "  call _ExitProcess@4\n"
         "%endmacro\n"
         "\n"
         "section .text\n"
         "\n"
         "; Entry point - calls the generated 'start' function\n"
         "global _start\n"
         "_start:\n"
         "  call start\n"
         "  push eax\n"
         "  call _ExitProcess@4\n"
         "\n";

#include "asm_prologue.h"

/***************************************************************************/

/* Win32 specific syscalls */

_lib << "\n"
        "; Windows print function - uses WriteFile (works with redirected "
        "output)\n"
        "print:\n"
        "  %define STD_OUTPUT_HANDLE -11\n"
        "  %define string ebp+8\n"
        "  %define handle ebp-4\n"
        "  %define length ebp-8\n"
        "  %define written ebp-12\n"
        "\n"
        "  begin 12\n"
        "\n"
        "  ; Get stdout handle\n"
        "  push dword STD_OUTPUT_HANDLE\n"
        "  call _GetStdHandle@4\n"
        "  mov [handle], eax\n"
        "\n"
        "  ; Calculate string length\n"
        "  addarg dword [string]\n"
        "  call strlen\n"
        "  clargs 1\n"
        "  mov [length], eax\n"
        "\n"
        "  ; WriteFile(handle, buffer, length, &written, NULL)\n"
        "  push dword 0\n"
        "  lea eax, [written]\n"
        "  push eax\n"
        "  push dword [length]\n"
        "  push dword [string]\n"
        "  push dword [handle]\n"
        "  call _WriteFile@20\n"
        "\n"
        "  return\n"
        "\n"
        "  %undef STD_OUTPUT_HANDLE\n"
        "  %undef string\n"
        "  %undef handle\n"
        "  %undef length\n"
        "  %undef written\n"
        "\n"
        "; Windows readline function - uses ReadFile (works with redirected "
        "input)\n"
        "readline:\n"
        "  %define STD_INPUT_HANDLE -10\n"
        "  %define buffer ebp+12\n"
        "  %define size ebp+8\n"
        "  %define handle ebp-4\n"
        "  %define bytesread ebp-8\n"
        "\n"
        "  begin 8\n"
        "\n"
        "  ; Get stdin handle\n"
        "  push dword STD_INPUT_HANDLE\n"
        "  call _GetStdHandle@4\n"
        "  mov [handle], eax\n"
        "\n"
        "  ; ReadFile(handle, buffer, size, &bytesread, NULL)\n"
        "  push dword 0\n"
        "  lea eax, [bytesread]\n"
        "  push eax\n"
        "  push dword [size]\n"
        "  push dword [buffer]\n"
        "  push dword [handle]\n"
        "  call _ReadFile@20\n"
        "\n"
        "  return\n"
        "\n"
        "  %undef STD_INPUT_HANDLE\n"
        "  %undef buffer\n"
        "  %undef size\n"
        "  %undef handle\n"
        "  %undef bytesread\n";

/* Generic lib */

#include "asm_lib.h"

/* No special footer needed - gcc linker handles PE creation */
